spring:
  application:
    name: gateway-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/v1/cart/**

            - id: authentication-service
              uri: lb://AUTHENTICATION-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/categories/**

            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**

server:
  port: 9090


jwt:
  secret:
    key: ${SECRET_KEY}