spring:
  application:
    name: payment-service


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true


  jackson:
    mapper:
      accept-case-insensitive-enums: true


server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      cartService:
        base-config: default
      OrderService:
        base-config: default