spring:
  datasource:
    url: jdbc:h2:mem:authentication_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: 'create-drop'


  flyway:
    enabled: false

eureka:
  client:
    enabled: false
