spring:
  application:
    name: order-service

  profiles:
    active: ${ACTIVE_PROFILES:dev}

server:
  port: 8082


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      productService:
        base-config: default
      inventoryService:
        base-config: default
      cartService:
        base-config: default