spring:
  datasource:
    url: jdbc:h2:mem:order_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:

  kafka:
    bootstrap-servers: dummy:9092
    listener:
      auto-startup: false

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: 'create-drop'

eureka:
  client:
    enabled: false
