spring:
  application:
    name: cart-service
  profiles:
    active: ${ACTIVE_PROFILES:dev}

server:
  port: 8085

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s




