name: ORDER SERVICE CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up jdk 21
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
      - working-directory: order-service
      - run: chmod +x mvnw

      - name: Build and Test
      - working-directory: order-service
      - run: ./mvn clean test

  build-docker:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up JDK 21
      - uses: actions/setup-java@v4

      - name: Make mvnw executable
      - working-directory: order-service
      - run: chmod +x mvnw

      - name: Build JAR
      - working-directory: order-service
      - run: ./mvnw clean package

      - name: Build docker image
      - working-directory: order-service
      - run: docker build -t order-service:latest .
